### ISSUE TITLE
Smooth animation

### ISSUE THREAD

**Issue by nova-nowiz** [rogeralmeida/revealjs-animated#2]
Hey,
I really like this project as it could give the same functionalities as PowerPoint or Keynote.

Is there a way to smooth animations?
Or are you planning to add this feature later?

**Comment by rogeralmeida** [comment]
Hey hey, sorry for the long delay to reply. At this moment I'm not planning to continue to maintain this project anymore.
Reveal.js now supports [Auto-Animate](https://revealjs.com/auto-animate/) which can achieve similar results.

**Comment by nova-nowiz** [comment]
Thanks!
